name: Build artifacts & deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'LICENSE.md'
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Run build
        run: bash buildDocs.sh

      - name: Deploy to GH-Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # or github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
